### ISSUE TITLE
Collapsible - Preselected section not working

### ISSUE THREAD

**Issue by mike-cao** [sherweb/ng2-materialize#116]
I am using the `mz-collapsible` component and am unable to have a preselected section opened on load. This issue is observable in the ng2-materialize demo app. Also, the HTML structure example on the demo app shows the `[active]="true` property on the `mz-collapsible-item-header` element when it's supposed to be on the `mz-collapsible-item` element as documented. Either way, it doesn't appear to work as described.

**Comment by scote** [comment]
It's an issue from Materialize. . They fix it on latest version. You can see their release note here : https://github.com/Dogfalo/materialize/releases. We did the update in master branch but the problem still persist with the preselected mz-collapsible item on our side. We will have to investigate more about this bug.

**Comment by mike-cao** [comment]
Thank you for looking into this!

**Comment by DarkIsDude** [comment]
Do you have any idea when you can fix it? Or how can I help you?

**Comment by charpeni** [comment]
The collapsible preselect bug has been fixed in [`0.98.2`](https://github.com/Dogfalo/materialize/releases/tag/v0.98.2) of materialize, we simply forgot to update the `yarn.lock` of the demo-app. It will be deployed on the next release.

Be sure you use the latest version of materialize and you can refer to our demo-app. 

I'll close this issue as it's fixed in master, feel free to ping us if it didn't work as expected.
