### ISSUE TITLE
Explain the benefits and reasoning behind using this vs Materialize directly?

### ISSUE THREAD

**Issue by IAMtheIAM** [sherweb/ng2-materialize#217]
Hi. This looks very good. My question is: what are the benefits to using this ng2 wrapper for Materialize over using Materialize directly. I see we get some directives (sugar syntax) for each component, but does this add any major benefit that can't be done with Materialize used directly in angular?

Thanks for any explanations.

**Comment by jfcere** [comment]
Hi @IAMtheIAM,

The main purpose of this library is to simplify the usage within the Angular framework which make it more dynamic. To illustrate what I mean, go ahead and play with the "Playground" sections of components like `MzInput` or `MzSelect` in [demo app](https://sherweb.github.io/ng2-materialize).

### Initialization
One thing that Materilize ask you to do for pretty much every components is to initialize it using JQuery. In our implementation, the initializations are done automatically without you to even know that you have to do so.

### Quirks
Materialize does not work perfectly "out of the box" when used with Angular, we had to fix a lot of "quirks".

For instance, for `mz-input` we handle the label so it can animate when the value is changed programmatically.

As another example, using `mz-select`, the communication between the dropdown created by Materialize and the native select HTML element is handle by our implementation otherwise there is a desynchronization between the value of `NgModel/NgControl` and the select element. This is just some examples of many more.

### Injection
Materialize modals ask you to put the modal HTML directly into the DOM while we offer the possibility to inject a component on the fly using [MzModalService](https://sherweb.github.io/ng2-materialize/modal).

### MediaService
We added the [MediaService](https://sherweb.github.io/ng2-materialize/media) that allow you to customize some behavior according to the view port size.

### Reactive Form support
Another nice advantage that we added to our implementation is the [Form Validation](https://sherweb.github.io/ng2-materialize/form-validation). Materialize only provide HTML5 validation while we added support for Reactive Form allowing a more flexible way to do form validation following the same Material Design guidelines.

### We haven't wrapped everything ...
Although we didn't wrapped everything yet, you still have all the Materialize library available for you to use when using our package. Some of the [CSS classes](https://sherweb.github.io/ng2-materialize/materialize-css-class) have not been wrapped into directive as it already does the work pretty well!

I hope it answers your question :)

**Comment by IAMtheIAM** [comment]
@jfcere Very excellent response! Thanks for the explanation. I think I will switch and try to use this ng2-materialize wrapper, it does seem to provide some good benefits for working with angular. :-D
