### ISSUE TITLE
Can I use this in my angular 4 project ? along with angular 2 materialize

### ISSUE THREAD

**Issue by Byloor** [sherweb/ng2-materialize#219]
@jsenecalatsherweb 
i am already using angular2-materialize in my angular 4 project. In the beginning everything looked fine, When I started with the forms then I noticed few of the fields doesnt work as it should like select ,datepicker etc (and it is not best idea to use jquery in angular)

 I am using reactive forms , If i install ng2-materialize, can I still use the my angular2-materialize for other components, (Since it is a large project , others are comfortable with angular2 materialize)

**Comment by jfcere** [comment]
In theory, the answer is **yes you should be** able to use both Angular2-Materialize and Ng2-Materialize at the same time, **but right now the answer is no** because Angular2-Materialize requires version 0.100.1 or higher of Materialize and or latest release uses 0.98.2.

We are about to release [v1.6.0](https://github.com/sherweb/ng2-materialize/milestone/2) which will use Materialize v0.100.2 and therefore will resolve the version gap between both libraries.

So **when  [v1.6.0](https://github.com/sherweb/ng2-materialize/milestone/2) will be released** you should be able to do so.

Just keep it mind that this would make your bundle bigger because Angular will have to include both librairies.

**Comment by jfcere** [comment]
[v1.6.0](https://github.com/sherweb/ng2-materialize/releases/tag/v1.6.0) has been released and we are now using Materialize v0.100.2 with JQuery 3.2
