### ISSUE TITLE
Global styling?

### ISSUE THREAD

**Issue by Nxt3** [sherweb/ng2-materialize#309]
How do you do global styling similar to how Material Angular does it?

https://material.angular.io/guide/theming

I've seen supposed examples on how to do this, but always come up dry.

**Comment by scote** [comment]
You have to override the scss file from Materialize and import your file in `.angular-cli.json` instead of Materialize scss file.

If you want to define new color palette you have to copy `_color.scss` file and your new color palette inside your new file.

You can copy `_variables.sccs`. In this file you can override individual component style.

Finally you will have to create a file which import your color and variable files.
```
@charset "UTF-8";

// Color
@import "assets/color";

// Variables;
@import "assets/variables";

// Basic Materialize imports
@import "node_modules/materialize-css/sass/materialize";
```

This will be this file you will include in your `.angular-cli.json` :
```
"styles": [
  "styles.scss",
+ "../assets/your-new-theme.scss"
],
```

**Comment by jfcere** [comment]
To add to @scote description, you can use http://mcg.mbitson.com to generate palettes from any color and use it in your custom `_color.scss` file.
